# Generated by Django 2.1.2 on 2019-05-01 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
            ],
        ),
        migrations.CreateModel(
            name='WorkerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('companyName', models.CharField(blank=True, max_length=130, null=True)),
                ('nationalIDNumber', models.CharField(blank=True, max_length=130, null=True)),
                ('service', models.CharField(blank=True, max_length=130, null=True)),
                ('buildingNumber', models.CharField(blank=True, max_length=130, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
