# Generated by Django 2.1.2 on 2019-05-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0002_auto_20190512_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workermodel',
            name='bank_name',
            field=models.CharField(choices=[('bank_BAI', 'BANCO ANGOLANO DE INVESTIMENTOS, S.A. BAI'), ('bank_YETU', 'BANCO YETU, S.A. YETU'), ('bank_BMF', 'BANCO BAI MICRO FINANÇAS, S.A. BMF'), ('bank_BIC', 'BANCO BIC, S.A. BIC'), ('bank_BCGA', 'BANCO CAIXA GERAL ANGOLA, S.A. BCGA'), ('bank_BCA', 'BANCO COMERCIAL ANGOLANO, S.A. BCA'), ('bank_BCH', 'BANCO COMERCIAL DO HUAMBO, S.A. BCH'), ('bank_BCI', 'BANCO DE COMÉRCIO E INDÚSTRIA, S.A. BCI'), ('bank_BDA', 'BANCO DE DESENVOLVIMENTO DE ANGOLA, S.A. BDA'), ('bank_BFA', 'BANCO DE FOMENTO ANGOLA, S.A. BFA'), ('bank_BIR', 'BANCO DE INVESTIMENTO RURAL, S.A. BIR'), ('bank_BNI', 'BANCO DE NEGÓCIOS INTERNACIONAL, S.A. BNI'), ('bank_BPC', 'BANCO DE POUPANÇA E CRÉDITO, S.A. BPC'), ('bank_BE', 'BANCO ECONÓMICO, S.A. BE'), ('bank_KEVE', 'BANCO KEVE, S.A. KEVE'), ('bank_BKI', 'BANCO KWANZA INVESTIMENTO, S.A. BKI'), ('bank_BPG', 'BANCO PRESTÍGIO, S.A. BPG'), ('bank_ATL', 'BANCO MILLENNIUM ATLÂNTICO, S.A. ATL'), ('bank_BSOL', 'BANCO SOL, S.A. BSOL'), ('bank_BVB', 'BANCO VALOR, S.A. BVB'), ('bank_VTB', 'BANCO VTB ÁFRICA, S.A. VTB'), ('bank_FNB', 'FINIBANCO ANGOLA, S.A. FNB'), ('bank_SBA', 'STANDARD BANK DE ANGOLA, S.A. SBA'), ('bank_SCBA', 'STANDARD CHARTERED BANK DE ANGOLA, S.A. SCBA'), ('bank_BCS', 'BCS – BANCO DE CRÉDITO DO SUL, S.A. BCS'), ('bank_BOCLB', 'BANCO DA CHINA LIMITADA – SUCURSAL EM LUANDA BOCLB')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='municipality',
            field=models.CharField(choices=[('CACUACO', 'Cacuaco'), ('KILAMBA', 'Kilamba-Kiaxi'), ('RANGEL', 'Rangel'), ('SAMBIZANGA', 'Sambizanga'), ('CAZENGA', 'Cazenga'), ('MAYANGA', 'Samba'), ('LUANDA', 'Luanda'), ('BELAS', 'Belas'), ('TALATONA', 'Talatona')], max_length=22),
        ),
        migrations.AlterField(
            model_name='workermodel',
            name='workdays',
            field=models.CharField(choices=[(0, 'Domingo'), (1, 'Segunda-Feira'), (2, 'Terça-Feira'), (3, 'Quarta-Feira'), (4, 'Quinta-Feira'), (5, 'Sexta-Feira'), (6, 'Sábado')], default=1, max_length=1, null=True),
        ),
    ]
