# Generated by Django 2.1.2 on 2019-05-19 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accs', '0003_auto_20190519_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workermodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='workermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '923 673 311'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="O número deve seguir o formato: '923 673 311'", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
