# Generated by Django 2.1.2 on 2019-05-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=200, null=True)),
                ('taskDescription', models.CharField(blank=True, max_length=200, null=True)),
                ('taskPrice', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taskTime', models.DateTimeField()),
                ('taskDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElectricityTaskModel',
            fields=[
                ('taskmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TaskModel')),
                ('electricOption', models.CharField(choices=[('MAINTANCE', 'Maintanance'), ('INSTALATION', 'Installation')], max_length=12)),
                ('electricArea', models.CharField(choices=[('BULB', 'Bulb Change'), ('SOCKET', 'Socket'), ('SWITCH', 'Switch'), ('EXTENSION', 'Extension'), ('SHOCK', 'Shock')], max_length=12)),
            ],
            bases=('main.taskmodel',),
        ),
        migrations.CreateModel(
            name='HouseCleaningTask',
            fields=[
                ('taskmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TaskModel')),
                ('extra_work', models.CharField(choices=[('CABINET', 'Inside Cabinet'), ('FRIDGE', 'Inside Fridge'), ('OVEN', 'Inside Oven'), ('WASHING', 'Laundry & Washing'), ('DOORS', 'Windows & Doors')], max_length=12)),
                ('numberOfRooms', models.IntegerField()),
                ('detergent', models.BooleanField(default=True)),
            ],
            bases=('main.taskmodel',),
        ),
        migrations.CreateModel(
            name='Plumbing',
            fields=[
                ('taskmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.TaskModel')),
                ('plumbingOption', models.CharField(choices=[('MAINTANCE', 'Maintanance'), ('INSTALATION', 'Installation')], max_length=12)),
                ('plumbingArea', models.CharField(choices=[('KITCHEN', 'Kitchen Sink'), ('BATH', 'Bathroom Pipes'), ('TOILET', 'Toilet Pipes'), ('SAWAGE', 'Sewage Pipes ')], max_length=12)),
            ],
            bases=('main.taskmodel',),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='customerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accs.CustomerModel'),
        ),
        migrations.AddField(
            model_name='taskmodel',
            name='ownerName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accs.WorkerModel'),
        ),
    ]
